### ISSUE TITLE
Fight or Fright Entries

### ISSUE THREAD

**Issue by Whayme** [bcook254/apex-legends-cache#101]
**Include a link to the cache file here**  
https://send.vis.ee/download/510a08f4ca33fc8e/#FhYXYEgBxNfWerD9zCVLcg

**How many entries did this cache file add during your merge?**  
Merging r5apex.dxvk-cache (1/2)... 17163 new entries
Merging r5apex (1).dxvk-cache (2/2)... 483 new entries
Writing 17646 entries to file output.dxvk-cache
Finished

**Would you like to be included in the cache file contributor list?**  
Yup, add it onto mine (Whom).

**Comment by it0na72** [comment]
How would one use this file? Just add it to the ./shadercache/1172470/DXVK_state_cache folder?
