### ISSUE TITLE
Apex Cash

### ISSUE THREAD

**Issue by NotTheTime** [bcook254/apex-legends-cache#105]
**Include a link to the cache file here**  
https://mega.nz/file/klVwAD5C#O0N2bWmK-HbJ89SByAe2eDBSckjZeTKxmpA4XrIvrsA

**How many entries did this cache file add during your merge?**  
I honestly have no idea. How do I even check that? (You know, for future times)

**Would you like to be included in the cache file contributor list?**  
Sure, here's my GitHub profile: https://github.com/NotTheTime

**Comment by bagusnl** [comment]
> **How many entries did this cache file add during your merge?**
> I honestly have no idea. How do I even check that? (You know, for future times)

https://github.com/bcook254/apex-legends-cache#open-an-issue
When you merge it with the current branch r5apex.dxvk-cache file it will tell you how many is added

**Comment by bcook254** [comment]
Thank you for you contribution! Sorry it took a little while to get around to merging this file, had a round of illness come through the household unfortunately.

> I honestly have no idea. How do I even check that?
When uploading a state cache file I ask that you run a merge with the repositories current r5apex.dxvk-cache file and your local r5apex.dxvk-cache file as a sanity check to make sure everything will merge up okay. This is done using a program called dxvk-cache-tool from [https://github.com/DarkTigrus/dxvk-cache-tool](https://github.com/DarkTigrus/dxvk-cache-tool). The output of the program will have a merged output.dxvk-cache file which should be uploaded and a link shared here.
