### ISSUE TITLE
Even more S15 cache

### ISSUE THREAD

**Issue by echoriiku** [bcook254/apex-legends-cache#120]
Cache file:
https://transfer.sh/k90ATH/output.dxvk-cache
Entries numbers:

> dxvk-cache-tool r5apex.dxvk-cache r5apex-local.dxvk-cache
Merging files r5apex.dxvk-cache r5apex-local.dxvk-cache
Detected state cache version v15
Merging r5apex.dxvk-cache (1/2)... 3989 new entries
Merging r5apex-local.dxvk-cache (2/2)... 32920 new entries
Writing 36909 entries to file output.dxvk-cache
Finished

**Would you like to be included in the cache file contributor list?** 
Yes, [my twitter](https://twitter.com/moodvaliant)

**Comment by bcook254** [comment]
It looks like you did not reset your cache file at the beginning of this season. This entails deleting it to remove old unused entries and starting a fresh file. Please confirm if you did or did not delete your old file as these entires *may* include the returning maps this season.

**Comment by echoriiku** [comment]
Oh, sorry, I did not deleted my old cache file, its the same from 2 seasons ago. Should I remove the issue?

**Comment by bcook254** [comment]
No worries! I am closing this issue now and look forward to your future
contributions.
