### ISSUE TITLE
Season 15 extra (returning maps are here)

### ISSUE THREAD

**Issue by RMED24** [bcook254/apex-legends-cache#122]
https://cdn.discordapp.com/attachments/786121802384015372/1039996291062714370/output.dxvk-cache

$ ./dxvk-cache-tool r5apex.dxvk-cache
Merging files r5apex.dxvk-cache
Detected state cache version v15
Merging r5apex.dxvk-cache (1/1)... 5356 new entries
Writing 5356 entries to file output.dxvk-cache
Finished

**I have merged the cache that was added like an hour ago, but I played some games since that merge**

I'm already credited just increase the entry count. Thanks!

**Comment by RMED24** [comment]
Was this forgotten or something?

**Comment by bcook254** [comment]
Sorry about that, for some reason the GitHub email notification missed my inbox. Am merging this now.
