### ISSUE TITLE
Cache contribution

### ISSUE THREAD

**Issue by harzival** [bcook254/apex-legends-cache#14]
Spent many an hour spectating people and auto-spinning while using grav cannon to build it up fast.

**Include a link to the cache file here**  
https://ovexon.com/r5apex.dxvk-cache
(its my server, an OVH box in France, its just in a webroot of a blank wordpress)

**How many entries did this cache file add during your merge?**  
1201

**Would you like to be included in the cache file contributor list?**  
Idc

Let me know if you want a website to do this I wouldn't mind making one if no one else is.

**Comment by bcook254** [comment]
> Let me know if you want a website to do this I wouldn't mind making one if no one else is.

For now I think we will keep using this repo as the central location. However, this will probably change in the future as more people contribute and each season comes and goes. As far as I know no one it making one at this time. I'll be sure to keep this offer in mind, there is much planning to do.

**Comment by harzival** [comment]
Cool cool, thanks for doing this, see you next map change
