### ISSUE TITLE
Cache not improving gameplay on Olympus

### ISSUE THREAD

**Issue by bcook254** [bcook254/apex-legends-cache#40]
> Seeing as we didn't have Olympus or World's Edge for the past week the lag would make sense for the next couple of days as we rebuild the cache file. I just hopped on with our latest cache file on World's Edge for the first time this season and I had very little stutter. This is why it is especially helpful to have more people contribute so we can build it back up again as quickly as possible.

after posting my previous comment, I've started my very first World's Edge game *ever* yesterday, and didn't have a single stutter. it looks like my issue is limited to Olympus at the moment, and trying to "play" it (by which I mean staring at a static screen for 5 minutes, and then doing the same after getting killed while spectating a teammate, with a few seconds of normal gameplay inbetween) multiple times has no effect on the issue. unless someone else has managed to play Olympus without frame drops using this cache, in which case I'll start looking for other explanations.

> This could be a couple of reasons I would imagine. Could be a hardware bottleneck from disk speed to cpu processing power. You might be accidentally not using Proton GE, or a spelling error in your command line args (this happened to me 🙄). I would say double check everything is installed and set up correctly. Otherwise, we have this cache file available for use!

I'm already using that file, and it's been working fine on every other map that I've tried so far. I don't really think it's an issue with something specific in my setup, given that before the recent update I played the map without any problems.

_Originally posted by @najodleglejszy in https://github.com/bcook254/apex-legends-cache/issues/30#issuecomment-1131924856_

**Comment by bcook254** [comment]
I moved this conversation in to a new issue to try and keep everything on topic.

I had a win the other day on Olympus using this cache file so I'm not exactly sure what happened on your end. Are you on Nvidia or AMD?

**Comment by bcook254** [comment]
Were you accidentally using an older cache file? We've had a few merges over the past couple of days, maybe that will help.

I also heard a rumor that AMD and Nvidia cache state files aren't compatible but I am not sure that is actually true since you had success on other maps.

And it's not a problem, the more information we can gather about how these cache files works for everyone and fix more issues the better it will be in the end.

**Comment by najodleglejszy** [comment]
> Were you accidentally using an older cache file? We've had a few merges over the past couple of days, maybe that will help.

no, I completely replaced my file with the new one, and I actually tried the most recent one available in the repo with the same result. the moment I reach the blue transition screen after the champion screen, the game almost completely locks up.

**Comment by najodleglejszy** [comment]
for the sake of completeness, this is how the textures look for me on Olympus. I've been stuck on that particular frame for about 5 minutes.

![Screenshot_20220520_201843](https://user-images.githubusercontent.com/8598559/169607163-22c1e456-8ed7-426b-86f0-fb8f96317708.png)

**Comment by bcook254** [comment]
Oh yikes! Have you attempted to delete the shader pre-cache (not the DXVK state cache file)? This is the entire folder structure under .../Steam/steamapps/shadercache/1172470
If you have pre-cache enabled, after you delete these it may download them and have to recompile them which will take a while.

**Comment by bcook254** [comment]
Dang, that's too bad. That's about all I can suggest off the top of my head. GL

**Comment by najodleglejszy** [comment]
I've just found a solution by a complete accident. all it took was a switch to a different AMD Vulkan driver (RADV instead of AMDVLK).

https://wiki.archlinux.org/title/Vulkan#Switching_between_AMD_drivers
