### ISSUE TITLE
File size is not right after doing a git pull?

### ISSUE THREAD

**Issue by GibsDev** [bcook254/apex-legends-cache#47]
I setup this repo in my DXVK_state_chache dir so that I could theoretically do a git pull every time there is an update. But for some reason the file is not even close to what it should be. dolphin says its 132 bytes, and it shows 6.73 MB on GitHub. Any ideas why this might be?

In the mean time I will just download it manually.

**Comment by bcook254** [comment]
If you are using git, make sure you have git-lfs installed and set up. https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage
