### ISSUE TITLE
673 entries

### ISSUE THREAD

**Issue by Hergeirs** [bcook254/apex-legends-cache#49]
**Include a link to the cache file here** 
https://drive.internxt.com/s/file/a487086fc9f1d2946857/e45de40505b8201511e507eb3b366621409f9054aef7455b5a339747036718cc 

**How many entries did this cache file add during your merge?**  
673 entries.

**Would you like to be included in the cache file contributor list?**  
Nope

**Comment by bcook254** [comment]
Merged in #52
