### ISSUE TITLE
New Cache Entry - 10.08.2022 | New Season 14 state cache version 15 can't merge

### ISSUE THREAD

**Issue by bagusnl** [bcook254/apex-legends-cache#69]
https://cdn.discordapp.com/attachments/827099523091660801/1006814728644997171/r5apex.dxvk-cache

New season seems to use newer state cache version that is not compatible to be merged from the one in the git file. I'm using ProtonGE-7.28 when making this cache, if that's has any relevancy.
```
$ ./dxvk-cache-tool r5apex.dxvk-cache r5apex-git.dxvk-cache -o apex-merged.dxvk-cache
Merging files r5apex.dxvk-cache r5apex-git.dxvk-cache
Detected state cache version v15
Merging r5apex.dxvk-cache (1/2)... 321 new entries
Error: Error { kind: InvalidInput, message: "State cache version mismatch: expected v15, found v10" }
```
**How many entries did this cache file add during your merge?**  
321 entries

**Would you like to be included in the cache file contributor list?**  
yes, [bagusnl](https://github.com/bagusnl)

**Comment by deep2p4ce** [comment]
Hey, thank you for contributing. Yes, with each major Apex update the old cache files get invalidated and for now we need to delete the old cache and let it rebuild from scratch. So the error message you got is to be expected. The owner of this repo just hasn't updated the online cache file to be the same state as the S14 patch. I could try to merge your cache file with my repo for now, so you can benefit also from my cache files.

**Comment by bagusnl** [comment]
> I could try to merge your cache file with my repo for now, so you can benefit also from my cache files.
That will be much appreciated. My setup is really low specs for Apex standard, not having proper dxvk-state cache has been quite hellish for me. Thank you

**Comment by deep2p4ce** [comment]
I merged your cache file with mine. And updated the contributor list. You added 47 entries to my cache file. And the total cache size is now 2749 entires. Hope this works until this repo gets updated. Cheers.
