### ISSUE TITLE
Cache addition with gungame maps

### ISSUE THREAD

**Issue by Whayme** [bcook254/apex-legends-cache#90]
**Include a link to the cache file here**  
[Link](https://send.vis.ee/download/0ef13363d0dba16e/#8_NGWmyReTgX5f1vpd5alw)

**How many entries did this cache file add during your merge?**  
```
Merging r5apex.dxvk-cache (1/2)... 14172 new entries
Merging r5apex(1).dxvk-cache (2/2)... 0 new entries
Writing 14172 entries to file output.dxvk-cache
```

**Would you like to be included in the cache file contributor list?**  
Yes, [Whom](https://blithefem.me/)

**Comment by Whayme** [comment]
This is just after a single session of matches, so it's likely there's a good amount that could be added if anyone else would like to play and contribute more.

**Comment by bcook254** [comment]
Thank you for the contribution! Before I merge this file I want to check if this was a fresh restart of the file. A couple seasons ago I decided to reset the cache file to save bandwidth and storage. Based on the number of entries I'm not sure if you did deleted your state cache file before playing again with the new maps. Please let me know.

**Comment by GustavoFenilli** [comment]
Even after updating the cache with this new one, I still have stutters.

**Comment by Whayme** [comment]
I did reset it then, I imagine all the new entries are from the new versions of existing maps for gungame.  That said, if people are still stuttering then you might want to do a reset from scratch again.

**Comment by bcook254** [comment]
Thank you for your contribution! I merged it with my reset cache file and had some overlapped entries so I believe these are valid. This was a huge contribution and should be a good base for the rest of this cache file.

@GustavoFenilli please ensure you are using either Proton Experimental or GE-Proton7-27 or later and check if you are still having any issues in the Gun Run game mode. BR may take a few more days to get to a smooth state.

**Comment by Whayme** [comment]
@GustavoFenilli Check #95, that should at least have some for some of the maps.
