### ISSUE TITLE
More Beast of Prey entries

### ISSUE THREAD

**Issue by Whayme** [bcook254/apex-legends-cache#95]
[Here](https://send.vis.ee/download/57c8d64ec7279334/#DdCzmM-3U_zIk61luDe9Yg) is another one with entries for at least one of the BR maps.  It's weird how our progress just gets reset randomly with updates that don't even seem to touch the maps.
```
Merging r5apex.dxvk-cache (1/2)... 15186 new entries
Merging r5apex(1).dxvk-cache (2/2)... 1224 new entries
Writing 16410 entries to file output.dxvk-cache
```

**Comment by bcook254** [comment]
Unfortunately its part of the Linux experience. Something in the compute and graphics pipeline changes with each update but we don't really have a way to determine that it is so here we are! At least this works for now.
